remove workflow caching for now

diff --git a/.github/workflows/build_latest.yml b/.github/workflows/build_latest.yml
--- a/.github/workflows/build_latest.yml
+++ b/.github/workflows/build_latest.yml
@@ -2,18 +2,18 @@ name: Build Latest
 
 on:
   push:
-    branches: ["main"]
+    branches: ['main']
     paths:
-      - "Cargo.toml"
-      - "Cargo.lock"
-      - "src/**"
-      - "parser/**"
-      - "site/**"
-      - "pad/**"
-      - "tests*/**"
-      - "changelog.md"
-      - "readme.md"
-      - ".github/workflows/build_latest.yml"
+      - 'Cargo.toml'
+      - 'Cargo.lock'
+      - 'src/**'
+      - 'parser/**'
+      - 'site/**'
+      - 'pad/**'
+      - 'tests*/**'
+      - 'changelog.md'
+      - 'readme.md'
+      - '.github/workflows/build_latest.yml'
 
 env:
   CARGO_TERM_COLOR: always
@@ -30,92 +30,56 @@ jobs:
   test_bin:
     runs-on: ubuntu-latest
     steps:
-    - uses: actions/checkout@v4
-    - uses: actions/cache@v4
-      with:
-        path: |
-          target/
-          !target/tmp/
-          !target/debug/incremental/
-        key: build-${{ runner.os }}-${{ hashFiles('Cargo.lock') }}
-        restore-keys: |
-          build-${{ runner.os }}-
-    - name: Run interpreter tests
-      run: cargo test --lib
+      - uses: actions/checkout@v4
+      - name: Run interpreter tests
+        run: cargo test --lib
   # Test the site
   test_site:
     runs-on: ubuntu-latest
     steps:
-    - uses: actions/checkout@v4
-    - uses: actions/cache@v4
-      with:
-        path: |
-          target/
-          !target/tmp/
-          !target/debug/incremental/
-        key: build-${{ runner.os }}-${{ hashFiles('Cargo.lock') }}
-        restore-keys: |
-          build-${{ runner.os }}-
-    - name: Run site tests
-      run: cargo test -p site
+      - uses: actions/checkout@v4
+      - name: Run site tests
+        run: cargo test -p site
   # Test ffi
   test_ffi:
     runs-on: ubuntu-latest
     steps:
-    - uses: actions/checkout@v4
-    - uses: actions/cache@v4
-      with:
-        path: |
-          target/
-          !target/tmp/
-          !target/debug/incremental/
-        key: build-${{ runner.os }}-${{ hashFiles('Cargo.lock') }}
-        restore-keys: |
-          build-${{ runner.os }}-
-    - name: Run site tests
-      run: cargo test -p tests_ffi
+      - uses: actions/checkout@v4
+      - name: Run site tests
+        run: cargo test -p tests_ffi
   # Build the site
   build_site:
     needs: test_site
     runs-on: ubuntu-latest
     steps:
-    - uses: actions/checkout@v4
-      with:
-        fetch-depth: 0
-        ref: main
-    - uses: actions/cache@v4
-      with:
-        path: |
-          target/
-          !target/tmp/
-          !target/debug/incremental/
-        key: build-${{ runner.os }}-${{ hashFiles('Cargo.lock', '.github/workflows/build_latest.yml') }}
-        restore-keys: |
-          build-${{ runner.os }}-
-    - name: Authenticate git
-      run: |
-        git config user.name "github-actions[bot]"
-        git config user.email "github-actions[bot]@users.noreply.github.com"
-        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
-    - name: Fetch site branch
-      run: git fetch origin site:site
-    - name: Install dependencies
-      run: |
-        rustup target add wasm32-unknown-unknown
-        cargo install trunk --locked --root target
-    - name: Build site
-      run: |
-        git checkout site
-        git branch --set-upstream-to=origin/site
-        git reset --hard origin/site
-        git rebase main || { echo "Rebase failed, aborting."; git rebase --abort; exit 1; }
-        cd site
-        cargo test -p site gen_blog_html
-        ../target/bin/trunk build --release -d ../docs
-        git add --all
-        git commit --amend --no-edit
-        git push --force
-        git checkout main
+      - uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+          ref: main
+      - name: Authenticate git
+        run: |
+          git config user.name "github-actions[bot]"
+          git config user.email "github-actions[bot]@users.noreply.github.com"
+          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
+      - name: Fetch site branch
+        run: git fetch origin site:site
+      - name: Install dependencies
+        run: |
+          rustup target add wasm32-unknown-unknown
+          cargo install trunk --locked --root target
+      - name: Build site
+        run: |
+          git checkout site
+          git branch --set-upstream-to=origin/site
+          git reset --hard origin/site
+          git rebase main || { echo "Rebase failed, aborting."; git rebase --abort; exit 1; }
+          cd site
+          cargo test -p site gen_blog_html
+          ../target/bin/trunk build --release -d ../docs
+          git add --all
+          git commit --amend --no-edit
+          git push --force
+          git checkout main
   # Create the release without assets
   create_release:
     name: Create release
@@ -124,18 +88,18 @@ jobs:
     env:
       GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
     steps:
-    - uses: actions/checkout@v4
-    - name: Delete old release
-      run: gh release delete latest --yes --cleanup-tag || true
-    - name: Prepare release notes
-      run: echo "This release contains binaries for the latest \`main\` branch." >> release_notes.md
-    - name: Create release
-      uses: softprops/action-gh-release@v1
-      with:
-        tag_name: latest
-        name: Latest Build
-        body_path: ./release_notes.md
-        prerelease: true
+      - uses: actions/checkout@v4
+      - name: Delete old release
+        run: gh release delete latest --yes --cleanup-tag || true
+      - name: Prepare release notes
+        run: echo "This release contains binaries for the latest \`main\` branch." >> release_notes.md
+      - name: Create release
+        uses: softprops/action-gh-release@v1
+        with:
+          tag_name: latest
+          name: Latest Build
+          body_path: ./release_notes.md
+          prerelease: true
   # Create the binaries and upload them as release assets
   create_binaries:
     name: Create binary
@@ -147,12 +111,37 @@ jobs:
       fail-fast: false
       matrix:
         include:
-          - { os: macos-latest,   target: x86_64-apple-darwin,       features: "audio,window"                   }
-          - { os: macos-latest,   target: aarch64-apple-darwin,      features: "audio,window"                   }
-          - { os: ubuntu-latest,  target: x86_64-unknown-linux-gnu,  features: "full"                           }
-          - { os: ubuntu-latest,  target: x86_64-unknown-linux-gnu,  features: "window",      name: "-no-audio" }
-          - { os: windows-latest, target: x86_64-pc-windows-msvc,    features: "full"                           }
-          - { os: windows-latest, target: aarch64-pc-windows-msvc,   features: "audio,window"                   }
+          - {
+              os: macos-latest,
+              target: x86_64-apple-darwin,
+              features: 'audio,window',
+            }
+          - {
+              os: macos-latest,
+              target: aarch64-apple-darwin,
+              features: 'audio,window',
+            }
+          - {
+              os: ubuntu-latest,
+              target: x86_64-unknown-linux-gnu,
+              features: 'full',
+            }
+          - {
+              os: ubuntu-latest,
+              target: x86_64-unknown-linux-gnu,
+              features: 'window',
+              name: '-no-audio',
+            }
+          - {
+              os: windows-latest,
+              target: x86_64-pc-windows-msvc,
+              features: 'full',
+            }
+          - {
+              os: windows-latest,
+              target: aarch64-pc-windows-msvc,
+              features: 'audio,window',
+            }
     steps:
       - uses: actions/checkout@v4
 
