add build site to actions

diff --git a/.github/workflows/build_latest.yml b/.github/workflows/build_latest.yml
--- a/.github/workflows/build_latest.yml
+++ b/.github/workflows/build_latest.yml
@@ -3,6 +3,15 @@ name: Build Latest
 on:
   push:
     branches: ["main"]
+    paths:
+      - "Cargo.toml"
+      - "Cargo.lock"
+      - "src/**"
+      - "site/**"
+      - "pad/**"
+      - "tests*/**"
+      - "changelog.md"
+      - "readme.md"
 
 env:
   CARGO_TERM_COLOR: always
@@ -16,16 +25,72 @@ concurrency:
 
 jobs:
   # Test the interpreter
-  test:
+  test_bin:
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v4
+    - uses: actions/cache@v4
+      with:
+        path: target
+        key: build-${{ runner.os }}-${{ hashFiles('Cargo.lock') }}
+        restore-keys: |
+          build-${{ runner.os }}-
     - name: Run interpreter tests
       run: cargo test --lib
+  # Test the site
+  test_site:
+    runs-on: ubuntu-latest
+    steps:
+    - uses: actions/checkout@v4
+    - uses: actions/cache@v4
+      with:
+        path: target
+        key: build-${{ runner.os }}-${{ hashFiles('Cargo.lock') }}
+        restore-keys: |
+          build-${{ runner.os }}-
+    - name: Run site tests
+      run: cargo test -p site
+  # Build the site
+  build_site:
+    needs: test_site
+    runs-on: ubuntu-latest
+    steps:
+    - uses: actions/checkout@v4
+      with:
+        fetch-depth: 0
+        ref: main
+    - uses: actions/cache@v4
+      with:
+        path: target
+        key: build-${{ runner.os }}-${{ hashFiles('Cargo.lock') }}
+        restore-keys: |
+          build-${{ runner.os }}-
+    - name: Authenticate git
+      run: |
+        git config user.name "github-actions[bot]"
+        git config user.email "github-actions[bot]@users.noreply.github.com"
+        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
+    - name: Fetch site branch
+      run: git fetch origin site:site
+    - name: Install dependencies
+      run: |
+        rustup target add wasm32-unknown-unknown
+        cargo install trunk --locked
+    - name: Build site
+      run: |
+        git checkout site
+        git reset --hard origin/site
+        git rebase main || { echo "Rebase failed, aborting."; git rebase --abort; exit 1; }
+        cd site
+        trunk build --release -d ../docs
+        git add --all
+        git commit --amend --no-edit
+        git push --force
+        git checkout main
   # Create the release without assets
   create_release:
     name: Create release
-    needs: test
+    needs: test_bin
     runs-on: ubuntu-latest
     env:
       GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
@@ -42,11 +107,10 @@ jobs:
         name: Latest Build
         body_path: ./release_notes.md
         prerelease: true
-
   # Create the binaries and upload them as release assets
   create_binaries:
     name: Create binary
-    needs: [test, create_release]
+    needs: [test_bin, create_release]
     runs-on: ${{ matrix.os }}
     env:
       BINARY_EXT: ${{ matrix.os == 'windows-latest' && '.exe' || '' }}
